symbols_equity:
  - SPY
  - QQQ
  - NVDA
  - AAPL
  - MSFT
  - META
  - TSLA
  - AMD
  - AMZN
  - GOOGL
  - NFLX
  - MU
  - SMCI
  - AVGO

symbols_crypto:
  - BTC-USD
  - ETH-USD
  - SOL-USD
  - XRP-USD
  - DOGE-USD
  - ADA-USD
  - AVAX-USD
  - LINK-USD
  - LTC-USD
  - DOT-USD

# model / indicators
ema_fast: 10
ema_mid: 20
ema_slow: 200
rsi_len: 14

# periods
period_1d: 180d

# thresholds (loosen for demo)
min_score_intraday: 0.45
min_score_swing: 0.50
min_avg_dollar_vol: 1000000

# guaranteed rows for demo/sales
fallback_top_n_intraday: 8
fallback_top_n_swing: 8
