[build]
# Tell Netlify the app lives in this subfolder
base    = "logiqsignals-site"
# After cd into base, publish from the Vite dist
publish = "dist"
# Run install & build inside base
command = "npm ci && npm run build"

[build.environment]
NODE_VERSION = "20"
