[build]
base = "logiqsignals-site"
command = "npm ci && npm run build"
publish = "dist"               # <-- fix: not logiqsignals-site/dist

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
